language: java
jdk: oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: eDL/xsSk90cfwpP3we6m78Vm/Ugxkqrz/EZiq+wY1qltdwGPSASGQApc+vpqhNqtdCSIKke8n5pILM963XL7JVzgDJ7y4lJG7K0mKjOmFmODs618NoMs/dWNSmmNIdSl7stUgcdn6sgCXvvVrffd0siZRtPNmyypejIgoxD9F6R3EyRLr+nWVFB9Xt4IuY7/6qhoRulg7eLTzCP7GCEZMxe0KSCucM097tKAX6CwOkkh/x/QyT5oa7PGj5WoncrpQLR4WWMoIvB2kqgTNZivcmHQQUsSvm0yESWB41EBaluIhOn1jETecm2m9IKu9+nJr5HCInI14stvQ7Nfp8N5i8oZWVLOVONU0sHnQzK2WsW56RzaDuMI/+A3jJXAe7BGT1SK2OE7J111u5KGgqZ8h3iExsmN4Ft+wO7FvVoXiHskUtUYDpuPZeaeeJob+O+1/yfvGMPAQ9rpJngCmH5DVd13VU2tgZR4By0OQ1lNgZ8CQUYT0y6x4fWsD46M45MfoQ734v8wXAHHO3fos30BtuLYJ+CkanB8N33GCJOsWaa9GPn0pP8y5BJN02FSEWJ6/1IGVn5OKcVcxDfKwW34BpWS9vPtzfsFQ6RkTKH2vrh7B03UcEJ+ilvnW6c6mAF+FyS0x3X687H+Z0SCDODHcuoT3dopkqcuhNhUEFO7zrk=
